services:
  mysql:
    image: mysql:8.0
    container_name: it4788_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/data
    restart: always

  mysql-test:
    image: mysql:8.0
    container_name: it4788_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: it4788_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - proxy-net

  group2-api:
    # image: ghcr.io/congktx/it4788:latest
    build: .
    container_name: it4788_app
    ports:
      - "${PORT}:${PORT}"
    env_file: .env.prod
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mysql
      - redis
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.group2-api.rule=Host(`group2.it4788.sukkaito.id.v\
        n`)"
      - "traefik.http.routers.group2-api.entrypoints=web"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
