name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER02_HOST }}
          username: ${{ secrets.SERVER02_USERNAME }}
          key: ${{ secrets.SERVER02_SSH_KEY }}
          script: |
            cd develop && cd IT4788

            git pull

            docker compose down

            docker compose -f 'docker-compose.yml' up -d --build 'elasticsearch' 
            docker compose -f 'docker-compose.yml' up -d --build 'redis' 
            docker compose -f 'docker-compose.yml' up -d --build 'app' 

            sleep 15

            docker compose exec -T app npm run migration:generate
            docker compose exec -T app npm run migration:run
